name: Build on Push
on: [push]

env:
  REGISTRY: ghcr.io 

jobs:
  build-bitnami-compat:
    runs-on: ubuntu-latest
    if: >-
      ${{ !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]')
      }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
         - APP: "etcd"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "3"
           VERSION: "3.5.1"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "bitnami-shell"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10"
           VERSION: "10"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "consul"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.11.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10"
           VERSION: "10.19.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "11"
           VERSION: "11.14.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "12"
           VERSION: "12.9.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "13"
           VERSION: "13.5.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "14"
           VERSION: "14.1.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.3"
           VERSION: "10.3.32"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.4"
           VERSION: "10.4.22"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.5"
           VERSION: "10.5.13"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.6"
           VERSION: "10.6.5"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb-galera"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.3"
           VERSION: "10.3.32"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb-galera"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.4"
           VERSION: "10.4.22"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb-galera"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.5"
           VERSION: "10.5.13"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb-galera"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.6"
           VERSION: "10.6.5"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "rabbitmq"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "3.9"
           VERSION: "3.9.13"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "minio"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "2022"
           VERSION: "2022.1.8"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "minio-client"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "2022"
           VERSION: "2022.1.25"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mysqld-exporter"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "0"
           VERSION: "0.13.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "consul-exporter"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "0"
           VERSION: "0.7.1"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cert-manager"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.7.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cert-manager-webhook"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.7.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "acmesolver"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.7.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cainjector"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.7.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "5.0"
           VERSION: "5.0.14"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "6.0"
           VERSION: "6.0.16"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "6.2"
           VERSION: "6.2.6"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-sentinel"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "5.0"
           VERSION: "5.0.14"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-sentinel"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "6.0"
           VERSION: "6.0.16"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-sentinel"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "6.2"
           VERSION: "6.2.6"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-cluster"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "5.0"
           VERSION: "5.0.14"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-cluster"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "6.0"
           VERSION: "6.0.16"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-cluster"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "6.2"
           VERSION: "6.2.6"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-exporter"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.34.1"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "tomcat"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "8.5"
           VERSION: "8.5.75"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "tomcat"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "9.0"
           VERSION: "9.0.58"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "tomcat"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10"
           VERSION: "10.0.16"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "elasticsearch"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "7"
           VERSION: "7.16.3"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "kafka"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "2"
           VERSION: "2.8.1"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "kafka"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "3"
           VERSION: "3.1.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "keycloak"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "16"
           VERSION: "16.1.1"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "memcached"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.6.13"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "fluentd"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.14.4"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Submodule init
        shell: bash
        run: git submodule init
      - name: Checkout bitnami recipe
        shell: bash
        run: git submodule update bitnami-docker-${{ matrix.APP }}
      # - name: Checkout bitnami recipe
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{ matrix.REPO_OWNER }}/bitnami-docker-${{ matrix.APP }}
      #     path: 'bitnami-docker-${{ matrix.APP }}'
      #     ref: master
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: repository
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            type=raw,value=${{ matrix.VERSION_MAJOR }}
            type=raw,value=${{ matrix.VERSION_MAJOR }}-${{ matrix.OS_FLAVOUR }}
            type=raw,value=${{ matrix.VERSION }}
            type=raw,value=${{ matrix.VERSION }}-${{ matrix.OS_FLAVOUR }}
            type=raw,value=${{ matrix.VERSION }}-${{ matrix.OS_FLAVOUR }}-r${{ matrix.REVISION }}
          images: ${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Update Dockerfile OS_ARCH
        shell: bash
        run: ./scripts/update.sh
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: bitnami-docker-${{ matrix.APP }}/${{ matrix.VERSION_MAJOR }}/${{ matrix.OS_FLAVOUR }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/cache/${{ matrix.APP }}:${{ matrix.VERSION }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/cache/${{ matrix.APP }}:${{ matrix.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
